export enum Role {
  All = 'All',
  Admin = 'Admin',
  cluster = 'cluster',
  Student = 'student',
  Superadmin = 'superadmin',
  department = 'department',
  Block = 'block_officer',
  State = 'state_officer',
  school = 'school',
  counsellor = 'trainer',
  skillCounsellor = 'skillTrainer',
  Manufacture = 'manufacture',
  Wholesaler='wholesaler',
  Retailer='retailer',
}
