export enum Role {
  All = 'All',
  Admin = 'admin',
  cluster = 'cluster',
  Student = 'student',
  Superadmin = 'superadmin',
  department = 'department',
  Block = 'block_officer',
  User = 'user',
  school = 'school',
  counsellor = 'trainer',
  skillCounsellor = 'skillTrainer',
  Manufacture = 'manufacture',
  Wholesaler='wholesaler',
  Retailer='retailer',
}
